# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7698002d2f8ed9e6a07ecd7f6618c1ae5a72736136c4cc478bafc8c394f9e00aba15714929c2a9a609179d5939968f6319a3df2fcb9dc11a5f05b2ec732a075b

test:
  secret_key_base: 69bfc692832d7d4a756c2503b0b7111009eb1d2b9e6b70c790294238e929655b812066b6d76d1b004e2ba91ae77e8d879d76b223dd183c288fff4c66bf89317d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
